export const skills = [
  "JavaScript",
  "React.js",
  "Node.js",
  "Next.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Java",
  "Springboot",
  "C++",
  "C#",
  "HTML",
  "CSS",
  "Tailwind",
  "Bootstrap",
  "MySQL",
  "PostreSQL",
  "MariaDB",
  "MongoDB",
  "Firebase",
  "DevOps",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "AWS",
  "Azure",
  "Cybersecurity",
  "Penetration Testing",
  "Network Security",
  "Machine Learning",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Data Structures & Algorithms",
  "Python",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "R Programming",
  "SQL & BigQuery",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Machine Learning & AI",
  "Statistical Analysis",
  "Business Intelligence",
  "BI",
  "Natural Language Processing",
  "NLP",
  "Predictive Analytics",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Wireframing & Prototyping",
  "Design Thinking",
  "UX Research",
  "Usability Testing",
  "Accessibility Standards",
  "SEO & SEM",
  "Social Media Marketing",
  "Content Creation",
  "Copywriting",
  "Blogging",
  "Email Marketing",
  "Google Ads & Facebook Ads",
  "Influencer Marketing",
  "Analytics",
  "Google Analytics",
  "HubSpot",
  "Project Management",
  "Agile & Scrum",
  "Business Strategy",
  "Market Research",
  "Financial Analysis",
  "Risk Management",
  "Business Communication",
  "Recruitment & Talent Acquisition",
  "Employee Relations",
  "Performance Management",
  "HR Analytics",
  "Compliance & Labor Laws",
  "Organizational Development",
  "Payroll & Benefits",
  "Financial Modeling",
  "Budgeting & Forecasting",
  "Taxation & Compliance",
  "Auditing",
  "Risk Assessment",
  "Investment Analysis",
  "Copywriting & Blogging",
  "SEO Writing",
  "Technical Writing",
  "Editing & Proofreading",
  "Research & Fact-Checking",
  "CAD Software (, )",
  "AutoCAD",
  "SolidWorks",
  "Robotics & Automation",
  "Embedded Systems",
  "Control Systems",
  "Manufacturing Processes",
];
