turtle_colors = [
    'AliceBlue', 'bisque3', 'CadetBlue', 'CornflowerBlue', 'DarkGrey', 'DarkSeaGreen',
    'AntiqueWhite', 'bisque4', 'CadetBlue1', 'cornsilk', 'DarkKhaki', 'DarkSeaGreen1',
    'AntiqueWhite1', 'black', 'CadetBlue2', 'cornsilk1', 'DarkMagenta', 'DarkSeaGreen2',
    'AntiqueWhite2', 'BlanchedAlmond', 'CadetBlue3', 'comsilk2', 'DarkOliveGreen',
    'DarkSeaGreen3', 'AntiqueWhite3', 'blue', 'CadetBlue4', 'cornsilk3', 'DarkOliveGreen1',
    'DarkSeaGreen4', 'AntiqueWhite4', 'blue1', 'chartreuse', 'cornsilk4', 'DarkOliveGreen2',
    'DarkSlateBlue', 'aquamarine', 'blue2', 'chartreuse1', 'cyan', 'DarkOliveGreen3',
    'DarkSlateGray', 'aquamarine1', 'blue3', 'chartreuse2', 'cyan1', 'DarkOrange',
    'DarkSlateGray1', 'aquamarine2', 'blue4', 'chartreuse3', 'cyan2', 'DarkOrange1',
    'DarkSlateGray2', 'aquamarine3', 'BlueViolet', 'chartreuse4', 'cyan3', 'DarkOrange2',
    'DarkSlateGray3', 'aquamarine4', 'brown', 'chocolate', 'cyan4', 'DarkOrange3',
    'DarkSlateGray4', 'azure', 'brown1', 'chocolate1', 'DarkBlue', 'DarkOrange4',
    'DarkSlateGrey', 'azure1', 'brown2', 'chocolate2', 'DarkCyan', 'DarkRed',
    'DarkTurquoise', 'azure2', 'brown3', 'chocolate3', 'DarkGoldenrod', 'DarkOrchid',
    'DarkViolet', 'azure3', 'brown4', 'chocolate4', 'DarkGoldenrod1', 'DarkOrchid1',
    'DeepPink', 'azure4', 'burlywood', 'coral', 'DarkGoldenrod2', 'DarkOrchid2',
    'DeepPink1', 'beige', 'burlywood1', 'coral1', 'DarkGoldenrod3', 'DarkOrchid3',
    'DeepPink2', 'bisque', 'burlywood2', 'coral2', 'DarkGoldenrod4', 'DarkOrchid4',
    'DeepPink3', 'bisque1', 'burlywood3', 'coral3', 'DarkGray', 'DarkRed',
    'DeepPink4', 'bisque2', 'burlywood4', 'coral4', 'DarkGreen', 'DarkSalmon',
    'DeepSkyBlue', 'DeepSkyBlue2', 'gold1', 'gray100', 'IndianRed1', 'LavenderBlush4',
    'LightGoldenrod', 'DeepSkyBlue3', 'gold2', 'green', 'IndianRed2', 'lawngreen',
    'LightGoldenrod1', 'DeepSkyBlue4', 'gold3', 'green1', 'IndianRed3', 'LawnGreen',
    'LightGoldenrod2', 'DimGray', 'gold4', 'green2', 'IndianRed4', 'lemonchiffon',
    'LightGoldenrod3', 'DimGrey', 'goldenrod', 'green3', 'ivory', 'LemonChiffon',
    'LightGoldenrod4', 'DodgerBlue', 'goldenrod1', 'green4', 'ivory1', 'LemonChiffon1',
    'LightGray', 'DodgerBlue1', 'goldenrod2', 'GreenYellow', 'ivory2', 'LemonChiffon2',
    'LightGreen', 'DodgerBlue2', 'goldenrod3', 'honeydew', 'ivory3', 'LemonChiffon3',
    'LightGrey', 'DodgerBlue3', 'goldenrod4', 'honeydew1', 'ivory4', 'LemonChiffon4',
    'LightPink', 'firebrick', 'gray0', 'honeydew2', 'khaki', 'LightBlue',
    'LightPink1', 'firebrick1', 'gray10', 'honeydew3', 'khaki1', 'LightBlue1',
    'LightPink2', 'firebrick2', 'gray20', 'hotpink', 'khaki2', 'LightBlue2',
    'LightPink3', 'firebrick3', 'gray30', 'HotPink', 'khaki3', 'LightBlue3',
    'LightPink4', 'firebrick4', 'gray40', 'HotPink1', 'lavender', 'LightCoral',
    'LightSalmon', 'FloralWhite', 'gray50', 'HotPink2', 'lavenderblush', 'LightCyan',
    'LightSalmon1', 'ForestGreen', 'gray60', 'HotPink3', 'LavenderBlush', 'LightCyan1',
    'LightSalmon2', 'gainsboro', 'gray70', 'HotPink4', 'LavenderBlush1', 'LightCyan2',
    'LightSalmon3', 'GhostWhite', 'gray80', 'indianred', 'LavenderBlush2', 'LightCyan3',
    'LightSalmon4', 'gold', 'gray90', 'IndianRed', 'LavenderBlush3', 'LightCyan4',
    'LightSeaGreen', 'LightSkyBlue', 'magenta', 'MediumPurple3', 'NavajoWhite4',
    'orchid1', 'PapayaWhip', 'LightSkyBlue1', 'magenta1', 'MediumPurple4', 'navy',
    'orchid2', 'PeachPuff', 'LightSkyBlue2', 'magenta2', 'MediumSeaGreen', 'NavyBlue',
    'orchid3', 'PeachPuff1', 'LightSkyBlue3', 'magenta3', 'MediumSlateBlue', 'OldLace',
    'orchid4', 'PeachPuff2', 'LightSkyBlue4', 'magenta4', 'MediumSpringGreen', 'OliveDrab',
    'PaleGoldenrod', 'PeachPuff3', 'LightSlateBlue', 'maroon', 'MediumTurquoise',
    'OliveDrab1', 'PaleGreen', 'PeachPuff4', 'LightSlateGray', 'maroon1',
    'MediumVioletRed', 'OliveDrab2', 'PaleGreen1', 'peru', 'LightSlateGrey', 'maroon2',
    'MidnightBlue', 'OliveDrab3', 'PaleGreen2', 'pink', 'LightSteelBlue', 'maroon3',
    'MidnightBlue', 'OliveDrab4', 'PaleGreen3', 'pink1', 'LightSteelBlue1', 'maroon4',
    'MintCream', 'orange', 'PaleGreen4', 'pink2', 'LightSteelBlue2', 'MediumAquamarine',
    'MistyRose', 'orange1', 'PaleTurquoise', 'pink3', 'LightSteelBlue3', 'MediumBlue',
    'MistyRose1', 'orange2', 'PaleTurquoise1', 'pink4', 'LightSteelBlue4', 'MediumOrchid',
    'MistyRose2', 'orange3', 'PaleTurquoise2', 'plum', 'LightYellow', 'MediumOrchid1',
    'MistyRose3', 'orange4', 'PaleTurquoise3', 'plum1', 'LightYellow1', 'MediumOrchid2',
    'MistyRose4', 'OrangeRed', 'PaleTurquoise4', 'plum2', 'LightYellow2', 'MediumOrchid3',
    'moccasin', 'OrangeRed1', 'PaleVioletRed', 'plum3', 'LightYellow3', 'MediumOrchid4',
    'NavajoWhite', 'OrangeRed2', 'PaleVioletRed1', 'plum4', 'LightYellow4', 'MediumPurple',
    'NavajoWhite1', 'OrangeRed3', 'PaleVioletRed2', 'PowderBlue', 'LimeGreen',
    'MediumPurple1', 'NavajoWhite2', 'OrangeRed4', 'PaleVioletRed3', 'purple', 'linen',
    'MediumPurple2', 'NavajoWhite3', 'orchid', 'PaleVioletRed4', 'purple1', 'purple2',
    'salmon1', 'SkyBlue', 'snow4', 'thistle4', 'wheat3', 'purple3', 'salmon2', 'SkyBlue1',
    'SpringGreen', 'tomato', 'wheat4', 'purple4', 'salmon3', 'SkyBlue2', 'SpringGreen1',
    'tomato1', 'white', 'red', 'salmon4', 'SkyBlue3', 'SpringGreen2', 'tomato2',
    'WhiteSmoke', 'red1', 'SandyBrown', 'SkyBlue4', 'SpringGreen3', 'tomato3', 'yellow',
    'red2', 'SeaGreen', 'SlateBlue', 'SpringGreen4', 'tomato4', 'yellow1', 'red3',
    'SeaGreen1', 'SlateBlue1', 'SteelBlue', 'turquoise', 'yellow2', 'red4', 'SeaGreen2',
    'SlateBlue2', 'SteelBlue1', 'turquoise1', 'yellow3', 'RosyBrown', 'SeaGreen3',
    'SlateBlue3', 'SteelBlue2', 'turquoise2', 'yellow4', 'RosyBrown1', 'SeaGreen4',
    'SlateBlue4', 'SteelBlue3', 'turquoise3', 'YellowGreen', 'RosyBrown2', 'seashell',
    'SlateGray', 'SteelBlue4', 'turquoise4', 'RosyBrown3', 'seashell1', 'SlateGray1',
    'tan', 'violet', 'RosyBrown4', 'seashell2', 'SlateGray2', 'tan1', 'VioletRed',
    'RoyalBlue', 'seashell3', 'SlateGray3', 'tan2', 'VioletRed1', 'RoyalBlue1', 'sienna',
    'SlateGray4', 'tan3', 'VioletRed2', 'RoyalBlue2', 'sienna1', 'snow', 'thistle',
    'VioletRed3', 'RoyalBlue3', 'sienna2', 'snow1', 'thistle1', 'wheat', 'SaddleBrown',
    'sienna3', 'snow2', 'thistle2', 'wheat1', 'salmon', 'sienna4', 'snow3'
]


